# Generated by Django 5.2.8 on 2025-12-27 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0002_cliente_empleado_producto_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Empleados',
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licoreria.clientes')),
                ('productos', models.ManyToManyField(to='licoreria.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(help_text='Descripción de lo prestado (envases, dinero, etc.)')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor monetario del préstamo', max_digits=10)),
                ('devuelto', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licoreria.clientes')),
            ],
        ),
    ]
