# Generated by Django 5.2.8 on 2025-12-28 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0004_distribuidores_detallesordenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='productos',
        ),
        migrations.AddField(
            model_name='ordenes',
            name='empleado',
            field=models.ForeignKey(blank=True, help_text='Vendedor que procesó la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, to='licoreria.empleados'),
        ),
        migrations.AddField(
            model_name='productos',
            name='distribuidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='licoreria.distribuidores'),
        ),
    ]
