# Generated by Django 5.2.8 on 2025-12-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0005_remove_ordenes_productos_ordenes_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('categoria_gasto', models.CharField(choices=[('PRO', 'Proveedores'), ('SER', 'Servicios Básicos'), ('NOM', 'Nómina'), ('OTR', 'Otros')], default='OTR', max_length=3, verbose_name='Categoría')),
            ],
        ),
    ]
