# Generated by Django 5.2.8 on 2026-01-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0006_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='codigo_unico',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
