# Generated by Django 5.2.8 on 2026-01-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0007_clientes_codigo_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código EAN/UPC'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_externo_api',
            field=models.CharField(blank=True, help_text='ID referencia en API externa', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Lista de ingredientes (para snacks)', null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='url_imagen_externa',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Imagen API'),
        ),
    ]
