# Generated by Django 5.2.8 on 2026-01-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0008_productos_codigo_barras_productos_id_externo_api_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/', verbose_name='Logo de la Marca')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='licoreria.marcas', verbose_name='Marca'),
        ),
    ]
