# Generated by Django 5.2.8 on 2026-01-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0010_listasprecios_empleados_codigo_unico_precioproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PUN', 'Puntos'), ('DES', 'Descuento'), ('REG', 'Regalo/Producto Gratis'), ('BON', 'Bono Especial')], default='PUN', max_length=3, verbose_name='Tipo de Recompensa')),
                ('descripcion', models.TextField(help_text='Descripción de la recompensa otorgada')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor monetario o puntos', max_digits=10)),
                ('fecha_otorgada', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite para usar la recompensa', null=True)),
                ('utilizada', models.BooleanField(default=False)),
                ('fecha_utilizacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas', to='licoreria.clientes')),
                ('orden_relacionada', models.ForeignKey(blank=True, help_text='Orden que generó esta recompensa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='licoreria.ordenes')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'ordering': ['-fecha_otorgada'],
            },
        ),
    ]
