# Generated by Django 5.2.8 on 2026-01-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0013_categorias_descripcion_categorias_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Ingredientes o descripción adicional del producto', null=True),
        ),
    ]
