# Generated by Django 5.2.8 on 2026-01-18 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0014_alter_productos_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensas',
            name='estado_solicitud',
            field=models.CharField(choices=[('PEND', 'Pendiente Aprobación'), ('APROB', 'Aprobada'), ('RECH', 'Rechazada'), ('ENTR', 'Entregada')], default='PEND', max_length=5, verbose_name='Estado de Solicitud'),
        ),
        migrations.AddField(
            model_name='recompensas',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recompensas',
            name='fecha_confirmacion_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recompensas',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recompensas',
            name='notas_supervisor',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Supervisor'),
        ),
        migrations.AddField(
            model_name='recompensas',
            name='solicitada_por_cliente',
            field=models.BooleanField(default=False, help_text='True si el cliente solicitó la recompensa'),
        ),
        migrations.AddField(
            model_name='recompensas',
            name='supervisor_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recompensas_aprobadas', to='licoreria.empleados'),
        ),
    ]
