# Generated by Django 5.2.8 on 2026-01-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0015_recompensas_estado_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='puntos_acumulados',
            field=models.IntegerField(default=0, help_text='1 punto por cada $10 gastados', verbose_name='Puntos de Fidelidad'),
        ),
    ]
