# Generated by Django 5.2.8 on 2026-01-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0016_clientes_puntos_acumulados'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensas',
            name='costo_puntos',
            field=models.IntegerField(default=0, help_text='Puntos necesarios para canjear', verbose_name='Costo en Puntos'),
        ),
    ]
