# Generated by Django 5.2.8 on 2026-01-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0017_recompensas_costo_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='pagada',
            field=models.BooleanField(default=False, verbose_name='Pagada'),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='puntos_asignados',
            field=models.BooleanField(default=False, verbose_name='Puntos Asignados'),
        ),
    ]
