# Generated by Django 5.2.8 on 2026-01-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0018_ordenes_pagada_ordenes_puntos_asignados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterUniqueTogether(
            name='productos',
            unique_together={('nombre', 'marca')},
        ),
    ]
