# Generated by Django 5.2.8 on 2026-01-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0019_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='sueldo',
        ),
    ]
