# Generated by Django 5.2.8 on 2026-01-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0020_remove_empleados_sueldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('id_externo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredientes', models.TextField(blank=True, null=True)),
                ('es_alcoholico', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='id_externo_api',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='url_imagen_externa',
        ),
    ]
