# Generated by Django 5.2.8 on 2026-01-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0021_cocteles_remove_productos_id_externo_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion_tecnica',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción OFF'),
        ),
        migrations.AddField(
            model_name='productos',
            name='origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País de Origen'),
        ),
        migrations.AddField(
            model_name='productos',
            name='url_imagen_externa',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Imagen Premium'),
        ),
    ]
