# Generated by Django 5.2.8 on 2026-01-18 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0022_productos_descripcion_tecnica_productos_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='limite_prestamo',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Límite máximo de préstamo ($)'),
        ),
        migrations.AddField(
            model_name='cocteles',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cocteles',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='coctel_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='licoreria.cocteles'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='producto_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='licoreria.productos'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='tipo',
            field=models.CharField(choices=[('LICO', 'Licores/Productos'), ('COCT', 'Cócteles'), ('DIN', 'Dinero/Efectivo'), ('ENV', 'Envases/Equipos')], default='LICO', max_length=4),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='descripcion',
            field=models.TextField(help_text='Descripción de lo prestado'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor monetario registrado', max_digits=10),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('modulo', models.CharField(max_length=100)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TARD', 'Pago Tardío'), ('DANO', 'Daño a Instalaciones/Equipos'), ('COMP', 'Comportamiento Inadecuado'), ('OTRO', 'Otras Sanciones')], default='TARD', max_length=4)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='licoreria.clientes')),
            ],
        ),
    ]
