# Generated by Django 5.2.8 on 2026-01-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0023_clientes_limite_prestamo_cocteles_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sku_api', models.CharField(max_length=100, unique=True)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('origen', models.CharField(choices=[('LICORES', 'OpenFoodFacts'), ('COCTELES', 'TheCocktailDB')], max_length=20)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
