# Generated by Django 5.2.8 on 2026-01-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0024_productoimportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='estado_solicitud',
            field=models.CharField(choices=[('PEND', 'Solicitado'), ('APROB', 'Vigente/Aprobado'), ('RECH', 'Rechazado'), ('DEVU', 'Devuelto/Finalizado')], default='PEND', max_length=5),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='fecha_limite_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de pago'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='solicitado_por_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='multas',
            name='tipo',
            field=models.CharField(choices=[('TARD', 'Pago Tardío de Orden'), ('DEVOL', 'Retraso en Devolución de Préstamo'), ('DANO', 'Daño a Instalaciones/Equipos'), ('COMP', 'Comportamiento Inadecuado'), ('OTRO', 'Otras Sanciones')], default='TARD', max_length=5),
        ),
    ]
