# Generated by Django 5.2.8 on 2026-01-19 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0025_prestamos_estado_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='limite_prestamo',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10, verbose_name='Límite máximo de préstamo ($)'),
        ),
        migrations.CreateModel(
            name='DetallesPrestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coctel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licoreria.cocteles')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='licoreria.prestamos')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licoreria.productos')),
            ],
            options={
                'verbose_name': 'Detalle de Préstamo',
                'verbose_name_plural': 'Detalles de Préstamos',
            },
        ),
    ]
