# Generated by Django 5.2.8 on 2026-01-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0026_alter_clientes_limite_prestamo_detallesprestamos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='coctel_relacionado',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='producto_relacionado',
        ),
        migrations.AddField(
            model_name='ordenes',
            name='codigo_orden',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='estado',
            field=models.CharField(choices=[('SOLI', 'Solicitando Préstamo'), ('PREST', 'Con Préstamo'), ('PAGD', 'Pagado'), ('MULT', 'Multado')], default='SOLI', max_length=5, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='DetallesPrestamos',
        ),
        migrations.DeleteModel(
            name='Prestamos',
        ),
    ]
