# Generated by Django 5.2.8 on 2026-01-19 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0027_remove_prestamos_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='codigo_orden',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=8, unique=True),
        ),
    ]
