# Generated by Django 5.2.8 on 2026-01-19 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0028_alter_ordenes_codigo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesordenes',
            name='coctel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licoreria.cocteles'),
        ),
        migrations.AlterField(
            model_name='detallesordenes',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licoreria.productos'),
        ),
    ]
