# Generated by Django 5.2.8 on 2026-01-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0029_detallesordenes_coctel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='estado',
            field=models.CharField(choices=[('SOLI', 'Solicitando Préstamo'), ('PREST', 'Con Préstamo'), ('PAGD', 'Pagado'), ('MULT', 'Multado'), ('CANC', 'Cancelada')], default='SOLI', max_length=5, verbose_name='Estado'),
        ),
    ]
