# Generated by Django 5.2.8 on 2026-01-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0030_alter_ordenes_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gastos',
        ),
    ]
