# Generated by Django 5.2.8 on 2026-01-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0031_delete_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensas',
            name='codigo_canje',
            field=models.CharField(blank=True, help_text='Código único para canjear en caja/factura', max_length=20, null=True, unique=True),
        ),
    ]
