# Generated by Django 5.2.8 on 2026-01-19 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0032_recompensas_codigo_canje'),
    ]

    operations = [
        migrations.AddField(
            model_name='multas',
            name='orden',
            field=models.ForeignKey(blank=True, help_text='Orden que originó la multa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='licoreria.ordenes'),
        ),
    ]
